### ISSUE TITLE
Create a java module for the SecretCredentialEncryptor

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/secure-key-storage#20] opened 2017-01-21 17:44 UTC
* Component to Encrypt the HMACKey with public key of the server (We might add this to the secret credential encryptor class)
  * SecretCredentialEncryptor
    * encrypt(hmacKey:JWK, serverPublicKey:JWK) : Base64EncodedJWE

**Comment by DGoAdorsys** [comment] 2017-02-17 14:08
Duplicate of #15

**Closed by DGoAdorsys** 2017-02-17 14:08 UTC
